# Generated by Django 2.2.3 on 2020-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200328_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
