# Generated by Django 2.2.3 on 2020-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200328_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
