# Generated by Django 2.2.3 on 2020-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_students_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='racks',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
