# Generated by Django 2.2.3 on 2020-03-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_students_racks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='racks',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
