# Generated by Django 2.2.3 on 2020-03-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200328_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='racks',
        ),
        migrations.AddField(
            model_name='students',
            name='rack1',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='rack2',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='rack3',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='rack4',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='students',
            name='rack5',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
